name: autotag
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  check-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check pypi versions
        uses: maybe-hello-world/pyproject-check-version@v3
        id: versioncheck
        with:
          pyproject-path: "./pyproject.toml"    # default value
      
      - name: check output
        id: versioncheck
        run: |
            echo "Output: ${{ steps.versioncheck.outputs.local_version_is_higher }}"  # 'true' or 'false
            echo "Local version: ${{ steps.versioncheck.outputs.local_version }}"     # e.g., 0.1.1
            echo "Public version: ${{ steps.versioncheck.outputs.public_version }}"   # e.g., 0.1.0
    outputs:
      do_publish: ${{ steps.versioncheck.outputs.local_version_is_higher }}
      new_version: ${{ steps.versioncheck.outputs.local_version }}

  tag:
    runs-on: ubuntu-latest
    needs: check-release
    if: ${{ needs.check-release.outputs.do_publish == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag-version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.RELEASE_TOKEN }}
          custom_tag: ${{ needs.check-release.outputs.new_version }}
