name: Release
on:
  push:
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read



jobs:
  release:
    name: release-all
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    permissions:
        contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Build and publish to pypi
      uses: JRubics/poetry-publish-action@v2.1
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}

    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4
    - uses: actions/download-artifact@v4
    - uses: ncipollo/release-action@v1
      with:
        body: ${{ steps.build_changelog.outputs.changelog }}
